// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Oog 2 - robotachtig

#ifndef _OOG_2___ROBOTACHTIG_UI_H
#define _OOG_2___ROBOTACHTIG_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void move_Animation(lv_obj_t * TargetObject, int delay);
void Rotatie_Animation(lv_obj_t * TargetObject, int delay);
void zoom_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_achtergrond_oog_2_png);    // assets/achtergrond oog 2.png
LV_IMG_DECLARE(ui_img_iris_png);    // assets/iris.png
LV_IMG_DECLARE(ui_img_puntjes_png);    // assets/puntjes.png
LV_IMG_DECLARE(ui_img_pupil_png);    // assets/pupil.png
LV_IMG_DECLARE(ui_img_glansjes_png);    // assets/glansjes.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
