// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Gekozen ogen - functies

#ifndef _GEKOZEN_OGEN___FUNCTIES_UI_H
#define _GEKOZEN_OGEN___FUNCTIES_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void Onderkantooglid_Animation(lv_obj_t * TargetObject, int delay);
void bovenkantooglid_Animation(lv_obj_t * TargetObject, int delay);
void vraagteken_Animation(lv_obj_t * TargetObject, int delay);
void Laden_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Sclera;
extern lv_obj_t * ui_Spinner_animatie;
extern lv_obj_t * ui_Pupil;
extern lv_obj_t * ui_Vraagteken_animatie;
extern lv_obj_t * ui_Ooglid_boven;
extern lv_obj_t * ui_Ooglid_onder;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_background_oog_png);    // assets/Background oog.png
LV_IMG_DECLARE(ui_img_oog_gekozen_8_gesplitst_png);    // assets/oog gekozen 8 gesplitst.png
LV_IMG_DECLARE(ui_img_vraagteken_png);    // assets/Vraagteken.png
LV_IMG_DECLARE(ui_img_bovenkant_ooglid_png);    // assets/Bovenkant ooglid.png
LV_IMG_DECLARE(ui_img_onderkant_ooglid_png);    // assets/Onderkant ooglid.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
